### ISSUE TITLE
why 14.04 instead of trusty?

### ISSUE THREAD

**Issue by odino** [dockerfile/ubuntu#5]
Hey guys,

this is maybe a stupid question, but is there a reason for `FROM ubuntu:14.04` rather than `FROM ubuntu:trustly`? Are they the same?

Cheers and sorry for the silly question! :)

**Comment by pilwon** [comment]
@odino they may or may not be the exact same image, but Trusty Tahr is the codename for 14.04 LTS.

**Comment by odino** [comment]
hey @pilwon my question was different :) it's kind of clear that they refer to the same major release, but I was wondering if there is any difference in using `14.04` rather than `trusty` :) I was thinking that probably using `trusty` you would get future updates like `14.04.xx`...but Im not sure if thats the case

**Comment by pilwon** [comment]
@odino All the other dockerfile images depend on this image, therefore the idea was to target and lock down to a specific version for stability.

**Comment by odino** [comment]
ah perfect, so its for stability! Then thanks for the clarification!
